Prog1 - stats file rewrite

diff --git a/Prog1/stats b/Prog1/stats
--- a/Prog1/stats
+++ b/Prog1/stats
@@ -1,211 +1,223 @@
 #!/bin/bash
-#Name: Marta Wegner
+#Name: Marta Ochoa
 #Class: CS344
 #Program 1
-#Description: This program calculates the mean
-#and median of both rows and columns input
+#Decription: This program calculates the mean and 
+#median of both rows and column input 
 #Input can be given as a file or as standard input
 
 
-#store name of temp file in TMP var
+#stores name of temp file in TMP var
 TMP=temp$$
 
-#remove temp file if error
+#remove temp fileif error
 trap "rm -f $TMP; exit 1" INT HUP TERM
 
-#If the user does not specifiy rows or cols
+#No arguments = the user did not specify
+#rows or columns
+#If the user does not specify rows or cols
 #print an error message
-if [ $# -eq 0 ] 
-   then 
-	echo "Must specify rows or cols" >&2
-	exit 1
-#if the user does not specify a file take input
-#store in temp file
-elif [ $# -eq 1 ]
-   then
-	#is a valid option is provided take input
-	if [[ "$1" == -r* ]] || [[ "$1" == -c* ]]
-	   then 
-		while read stdInp
-		do 
-	   	   echo $stdInp >> $TMP
-		done
-	#if -r or -c is not specified give error
-	else 
- 	   echo "Invalid command" >&2
+if [ $# -eq 0 ]
+	then 
+	   echo "Must specify a rows or colums" >&2
 	   exit 1
-	fi
-#If the file cannot be read
-#print error message
+#If only one arg = no file
+#If the user does not specify a file take input
+#Store input in temp file
+elif [ $# -eq 1 ]
+	then
+	   #if a valid option is provided [row or
+	   #column] take input
+	   if [[ "$1" == -r* ]] || [[ "$1" == -c* ]]
+	      then
+		#While there is input from the 
+		#user read it into the tmp file
+		while read stdInp
+		do
+		   echo $stdInp >> $TMP
+		done
+	   #if -r or -c is not specified give
+	   #error
+	   else
+	      echo "Invalid command" >&2
+	      exit 1
+	   fi
+#Test if file has read permissions
+#If the file cannot be read print error
 elif [ ! -r "$2" ]
-   then
-	echo "Error opening file" >&2
-	exit 1
-#If the file can be read transfer contents
-#to a temp file
+	then
+	   echo "Error opening file" >&2
+	   exit 1
+#Else if  there are 2 args then
+#there is a file that can can be read
+#Transfer contents of file to temp file
 elif [ $# -eq 2 ]
-   then
-	cp $2 $TMP
-#Else the user gave the wrong # of arguments
-else 
-   echo "Wrong number of arguments" >&2
-   exit 1
+	then 
+	   cp $2 $TMP
+#Else the user gave the wrong # of args
+else
+	echo "Wrong number of arguments" >&2
+	exit 1
 fi
 
-#if rows sepcified
+#If rows specified
 if [[ "$1" == -r* ]]
-   then
-   rowCnt=0
-   while read line
-   do
-	sum=0
-	colCnt=0
+	then 
+	   rowCnt=0 #count of the number of rows
+	   while read line
+	   do
+	      sum=0 #sum of the row
+	      colCnt=0 #count of the number of cols
 
-	#get each # in the line into var x
-	for x in $line
-	do
-	  #add x to sum of row
-	  sum=`expr $sum + $x`
-	
-	  #add x to array for the line
-	  lineArr[$colCnt]=$x
+	      #get each # in the line into var x
+	      for x in $line
+	      do
+		#add x tto sum of row
+		sum=`expr $sum + $x`
 
-	  #increase col cnt for each #(col)
-	  colCnt=`expr $colCnt + 1`
-	done 
+		#add x to array for the line
+		lineArr[$colCnt]=$x
 
-	#calculate average of row from sum
-	avg=`expr $sum / $colCnt`
+		#incread col cnt for each #(col)
+		colCnt=`expr $colCnt + 1`
+	      done
+	      
+	      #calculate avg of row from sum
+	      avg=`expr $sum / $colCnt`
 
-	#round average if needed
-	mod=`expr $sum % $colCnt`
-	if [ `expr 2 \* $mod` -ge $colCnt ]
-	   then
-		avg=`expr $avg + 1`
-	fi
-	
-	#store avg in array
-	avgArr[$rowCnt]=$avg
+	      #round avg if needed
+	      mod=`expr $sum % $colCnt`
+	      if [ `expr 2 \* $mod` -ge $colCnt ]
+		then
+		   avg=`expr $avg + 1`
+	      fi
 
-	#calculate median
-	#sort row from lineArr
-	sorted=( $(
+	      #store avg in array
+	      avgArr[$rowCnt]=$avg
+
+	      #calculate median
+	      #sort row from lineArr
+	      #store in sorted
+	      sorted=( $(
 		for y in "${lineArr[@]}"
 		do
 		   echo "$y"
 		done | sort -n) )
 
-	#find middle
-	middle=`expr $colCnt / 2`
-	med=${sorted[$middle]}
+	      #find middle
+	      middle=`expr $colCnt / 2`
+	      med=${sorted[$middle]}
 
-	#store median in array
-	medArr[$rowCnt]=$med
+	      #store median in array
+	      medArr[$rowCnt]=$med
 
-	#increase the row cnt for each line read
-	rowCnt=`expr $rowCnt + 1`
-   done < "$TMP"
+	      #increase the row cnt for each line read
+	      rowCnt=`expr $rowCnt + 1`
+	   done < "$TMP"
 
-   #print results
-   echo "Average Median"
-   for ((i=0;i<$rowCnt;i++))
-	do
-  	   echo "${avgArr[$i]}	${medArr[$i]}"
-	done
+	   #print results
+	   echo "Average Median"
+	   for ((i=0;i<$rowCnt;i++))
+	      do
+		echo "${avgArr[$i]}      ${medArr[$i]}"
+	      done
 
-#if cols specified
+#If cols specified
 elif [[ "$1" == -c* ]]
-   then
-	rowCnt=0
-	declare -A colArr
-   	while read line
-   	do
-           colCnt=0
-
-	   #increase the row cnt for each line read
-	   rowCnt=`expr $rowCnt + 1`
-
-	   #get each # in the line into var x
-	   for x in $line
+	then
+	   rowCnt=0
+	   declare -A colArr
+	   while read line
 	   do
-	     #add x to sum of col in array
-	     sum=${colSum[$colCnt]}
-	     sum=`expr $sum + $x`
-	     colSum[$colCnt]=$sum
-	
-	     #Add x to colArr
-	     colArr[$colCnt,$rowCnt]=$x
+	      colCnt=0
+	     
+	      #increase the row cnt for each line read
+	      rowCnt=`expr $rowCnt + 1`
+ 
+	      #get each # in the line into var x
+	      for x in $line
+	      do
+		#add x to sum of col in array
+		#sum = current sum of column
+		sum=${colSum[$colCnt]}
+		#add x  to sum to get updated sum
+		sum=`expr $sum + $x`
+		#put new sum into array
+		colSum[$colCnt]=$sum
 
-	     #increase col cnt for each #(col)
-	     colCnt=`expr $colCnt + 1`
+		#Add x to colArr
+		colArr[$colCnt,$rowCnt]=$x
+
+		#increase col cnt for each #(col)
+		colCnt=`expr $colCnt + 1`
+	      done
+	   done < "$TMP"
+
+	   #calculate average of col from colSum array
+	   colCnt=0
+	   for i in ${colSum[@]}
+	   do
+	      avg=`expr $i / $rowCnt`
+
+	      #round if needed
+	      mod=`expr $i % $rowCnt`
+	      if [ `expr 2 \* $mod` -ge $rowCnt ]
+	      then
+		avg=`expr $avg + 1`
+	      fi
+
+	      #store avg in array
+	      avgArr[$colCnt]=$avg
+	      colCnt=`expr $colCnt + 1`
 	   done
 
-	done < "$TMP" 
-
-	#calculate average of col from colSum array
-	colCnt=0
-	for i in ${colSum[@]}
-	do
-	   avg=`expr $i / $rowCnt`
-
-	   #round if needed
-	   mod=`expr $i % $rowCnt`
-	   if [ `expr 2 \* $mod` -ge $rowCnt ]
-	       then
-	       	   avg=`expr $avg + 1`
-	   fi
-	
-	   #store avg in array
-	   avgArr[$colCnt]=$avg
-	  colCnt=`expr $colCnt + 1`
-	done 
-
-	#calculate median
-	#sort cols from colArr - each row is a col
-	for ((i=0;i<colCnt;i++))
-	do
-	   for ((j=1;j<=rowCnt;j++))
+	   #calculate median
+	   #sort cols from colArr - each row is a col
+	   for ((i=0;i<colCnt;i++))
 	   do
+	      for ((j=1;j<=rowCnt;j++))
+	      do
 		lineArr[$j]=${colArr[$i,$j]}
-	   done
-	
-	#sort col
-	sorted=( $(
-		for y in "${lineArr[@]}"
-		do
+	      done
+
+	      #sort col
+	      sorted=( $(
+	         for y in "${lineArr[@]}"
+	         do
 		   echo "$y"
-		done | sort -n) )
+	         done | sort -n) )
 
-	#find middle
-	middle=`expr $rowCnt / 2`
-	med=${sorted[$middle]}
+	      #find middle
+	      middle=`expr $rowCnt / 2`
+	      med=${sorted[$middle]}
 
-	#store median in array
-	medArr[$i]=$med 
-	done
+	      #store median in array
+	      medArr[$i]=$med
+	   done
 
-        #print results
-   	echo "Average: "
-    	for i in ${avgArr[@]}
-	do
-  	   printf "$i "
-	done
-
-	printf "\n"
-
-   	echo "Median: "
-   	for i in ${medArr[@]}
+	   #print results
+	   echo "Average: "
+	   for i in ${avgArr[@]}
 	   do
-  	      printf "$i "
-	done
+	      printf "$i "
+	   done
 
-	printf "\n"
+	   printf "\n"
 
-#if invalid command specified print error
-else 
-   echo "Invalid command" >&2
-   rm -f $TMP
-   exit 1
+	   echo "Median: "
+	   for i in ${medArr[@]}
+	   do
+	      printf "$i "
+	   done
+
+	   printf "\n"
+
+#else an invalid command was specified
+#print an error
+else
+	echo "Invalid command" >&2
+	rm -f $TMP
+	exit 1
 fi
 
 #if completed successfully, remove temp file and exit
